schema_version: 1

context:
  name: faker-vehicle
  version: 0.2.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/faker_vehicle-${{ version }}.tar.gz
  sha256: 3a7f1065da54b998f8875785282d3b1da4a422bc14fe0776a4a4ff4c1872a3b5

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
  run:
    - faker
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - faker_vehicle
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: Vehicle related Provider for the Faker Python package.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/kennethwsmith/faker_vehicle

extra:
  recipe-maintainers:
    - janjagusch
